name: Ej1 workflow


on: push

jobs:
  probar:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v5
        
      - name: Instalar pytest
        run: pip install pytest
        
      - name: Ejecutar test
        run: pytest test.py
